import type { Metadata } from 'next';
import { Fira_Code, Montserrat, Poppins } from 'next/font/google';
import './globals.scss';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});
const fira = Fira_Code({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-fira',
  weight: [ '300', '400', '500', '600', '700']
});

const montSerrate = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-fira',
  weight: [ '300', '400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: 'Kauan Portfólio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={fira.className}>{children}</body>
    </html>
  )
}
