import type { Metadata } from 'next'
import { useTranslations } from 'next-intl'
import About from '../about-me/about'
import Connect from '../contact/page'
import Education from '../education/page'
import NavbarComponent from '../navbar/page'
import Presentation from '../presentation/page'
import Project from '../project/page'
import Skills from '../skills/page'

export const metadata: Metadata = {
  title: 'Kauan Dev',
  description: 'Generated by create next app',
}

export default function Home() {
  const t = useTranslations('presentation')
  return (
    <>
      <NavbarComponent></NavbarComponent>
      {/* <h1>{t('i_am')}</h1> */}
      <Presentation developer={t('developer')} i_am={t('i_am')} ></Presentation>
      <About></About>
      <Education></Education>
      <Skills></Skills>
      <Project></Project>
      <Connect></Connect>
    </>
  )
}



